// Exemples de présentation. Ces objets ne sont ni une session ni des données serveur.
export const agency = {
  name: "ImmoKer Agence Abidjan",
  manager: "Kouadio Bernard",
  initials: "KB",
  date: "mercredi 9 septembre",
};
export const owners = [
  "Aminata Diallo",
  "Kofi Mensah",
  "Marie-Claire Koffi",
  "Ibrahim Coulibaly",
];
export const properties = [
  {
    id: "imk-001",
    reference: "IMK-001",
    address: "12 Rue des Bougainvilliers",
    location: "Cocody, Abidjan",
    type: "appartement",
    area: 85,
    rooms: 3,
    bedrooms: 2,
    rentLabel: "350 000 FCFA",
    deposit: "700 000 FCFA",
    availableFrom: "01/02/2024",
    owner: owners[0],
    ownerPhone: "+225 07 12 34 56",
    status: "Occupé",
    tone: "info",
    published: false,
    dossierId: "jean",
    image: {
      uri: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1000&q=85",
    },
    description:
      "Bel appartement lumineux dans une résidence sécurisée, au cœur de Cocody. Idéal pour famille ou couple.",
  },
  {
    id: "imk-002",
    reference: "IMK-002",
    address: "45 Avenue Houphouët-Boigny",
    location: "Plateau, Abidjan",
    type: "studio",
    area: 35,
    rooms: 1,
    bedrooms: 1,
    rentLabel: "180 000 FCFA",
    deposit: "360 000 FCFA",
    availableFrom: "01/03/2024",
    owner: owners[0],
    ownerPhone: "+225 07 12 34 56",
    status: "Publié",
    tone: "success",
    published: true,
    views: 89,
    publishedAt: "10/02/2024",
    image: {
      uri: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1000&q=85",
    },
    description:
      "Studio moderne au Plateau, idéal pour professionnel ou étudiant. Vue dégagée.",
  },
  {
    id: "imk-003",
    reference: "IMK-003",
    address: "Riviera 3",
    location: "Riviera 3, Abidjan",
    type: "appartement",
    area: 90,
    rooms: 3,
    bedrooms: 2,
    rentLabel: "450 000 FCFA",
    deposit: "900 000 FCFA",
    availableFrom: "01/04/2024",
    owner: owners[1],
    ownerPhone: "+225 07 22 33 44",
    status: "Candidatures",
    tone: "pending",
    published: true,
    views: 120,
    publishedAt: "01/02/2024",
    description: "Appartement de démonstration à Riviera 3.",
  },
  {
    id: "imk-004",
    reference: "IMK-004",
    address: "Marcory",
    location: "Marcory, Abidjan",
    type: "appartement",
    area: 60,
    rooms: 2,
    bedrooms: 1,
    rentLabel: "250 000 FCFA",
    deposit: "500 000 FCFA",
    availableFrom: "01/02/2024",
    owner: owners[2],
    ownerPhone: "+225 07 44 55 66",
    status: "Occupé",
    tone: "info",
    published: false,
    dossierId: "mariam",
    description: "Appartement de démonstration à Marcory.",
  },
  {
    id: "imk-005",
    reference: "IMK-005",
    address: "Cocody Angré",
    location: "Cocody Angré, Abidjan",
    type: "studio",
    area: 28,
    rooms: 1,
    bedrooms: 1,
    rentLabel: "120 000 FCFA",
    deposit: "240 000 FCFA",
    availableFrom: "01/05/2024",
    owner: owners[2],
    ownerPhone: "+225 07 44 55 66",
    status: "Disponible",
    tone: "pending",
    published: false,
    description: "Studio de démonstration à Cocody Angré.",
  },
  {
    id: "imk-006",
    reference: "IMK-006",
    address: "Treichville",
    location: "Treichville, Abidjan",
    type: "appartement",
    area: 55,
    rooms: 2,
    bedrooms: 1,
    rentLabel: "200 000 FCFA",
    deposit: "400 000 FCFA",
    availableFrom: "01/05/2024",
    owner: owners[3],
    ownerPhone: "+225 07 77 88 99",
    status: "Brouillon",
    tone: "neutral",
    published: false,
    description: "Appartement fonctionnel à Treichville.",
  },
];
export const applications = [
  {
    id: "oumar",
    name: "Oumar Traoré",
    initials: "OT",
    date: "14/02/2024",
    email: "oumar.t@email.com",
    phone: "+225 07 11 22 33",
    propertyId: "imk-002",
    propertyLabel: "IMK-002 - Plateau",
    status: "Nouvelle",
    tone: "pending",
  },
  {
    id: "fatou",
    name: "Fatou Bamba",
    initials: "FB",
    date: "10/02/2024",
    email: "fatou@example.com",
    phone: "+225 07 22 33 44",
    propertyId: "imk-003",
    propertyLabel: "IMK-003 - Riviera 3",
    status: "En cours",
    tone: "warning",
  },
  {
    id: "sekou",
    name: "Sékou Koné",
    initials: "SK",
    date: "09/02/2024",
    email: "sekou@example.com",
    phone: "+225 07 33 44 55",
    propertyId: "imk-003",
    propertyLabel: "IMK-003 - Riviera 3",
    status: "En cours",
    tone: "warning",
  },
  {
    id: "aicha",
    name: "Aïcha Dembélé",
    initials: "AD",
    date: "12/02/2024",
    email: "aicha@example.com",
    phone: "+225 07 44 55 66",
    propertyId: "imk-002",
    propertyLabel: "IMK-002 - Plateau",
    status: "Refusée",
    tone: "danger",
  },
];
export const dossiers = [
  {
    id: "jean",
    name: "Jean Dupont",
    initials: "JD",
    email: "jean.dupont@email.com",
    propertyId: "imk-001",
    period: "Jan 2024 — Mar 2024",
  },
  {
    id: "mariam",
    name: "Mariam Coulibaly",
    initials: "MC",
    email: "mariam@example.com",
    propertyId: "imk-004",
    period: "Fév 2024",
  },
];
export const documents = [
  {
    id: "lease",
    dossierId: "jean",
    title: "Bail Jean Dupont - IMK-001",
    metadata: "2.4 MB · 08/01/2024",
  },
  {
    id: "receipt-jan",
    dossierId: "jean",
    title: "Quittance Janvier 2024",
    metadata: "0.5 MB · 31/01/2024",
  },
  {
    id: "receipt-feb",
    dossierId: "jean",
    title: "Quittance Février 2024",
    metadata: "0.5 MB · 28/02/2024",
  },
  {
    id: "identity",
    dossierId: "jean",
    title: "CNI Jean Dupont",
    metadata: "1.2 MB · 08/01/2024",
  },
];
export const payments = [
  {
    id: "p1",
    dossierId: "jean",
    period: "Février 2024",
    amountValue: 350000,
    amount: "350 000 FCFA",
    due: "01/02/2024",
    status: "Payé",
    tone: "success",
    propertyLabel: "IMK-001 — Cocody",
    owner: owners[0],
    tenant: "Jean Dupont",
  },
  {
    id: "p2",
    dossierId: "jean",
    period: "Janvier 2024",
    amountValue: 350000,
    amount: "350 000 FCFA",
    due: "01/01/2024",
    status: "Payé",
    tone: "success",
    propertyLabel: "IMK-001 — Cocody",
    owner: owners[0],
    tenant: "Jean Dupont",
  },
  {
    id: "p3",
    dossierId: "jean",
    period: "Mars 2024",
    amountValue: 350000,
    amount: "350 000 FCFA",
    due: "01/03/2024",
    status: "En attente",
    tone: "warning",
    propertyLabel: "IMK-001 — Cocody",
    owner: owners[0],
    tenant: "Jean Dupont",
  },
  {
    id: "p4",
    dossierId: "mariam",
    period: "Février 2024",
    amountValue: 250000,
    amount: "250 000 FCFA",
    due: "01/02/2024",
    status: "En retard",
    tone: "danger",
    propertyLabel: "IMK-004 — Marcory",
    owner: owners[2],
    tenant: "Mariam Coulibaly",
  },
  {
    id: "p5",
    dossierId: "mariam",
    period: "Janvier 2024",
    amountValue: 250000,
    amount: "250 000 FCFA",
    due: "01/01/2024",
    status: "Payé",
    tone: "success",
    propertyLabel: "IMK-004 — Marcory",
    owner: owners[2],
    tenant: "Mariam Coulibaly",
  },
  {
    id: "p6",
    dossierId: "mariam",
    period: "Mars 2024",
    amountValue: 250000,
    amount: "250 000 FCFA",
    due: "01/03/2024",
    status: "En attente",
    tone: "warning",
    propertyLabel: "IMK-004 — Marcory",
    owner: owners[2],
    tenant: "Mariam Coulibaly",
  },
];
export const contractExample = {
  firstName: "Kouassi",
  lastName: "Abo",
  email: "kouassi.abo@email.com",
  phone: "+225 07 55 44 33",
  startDate: "04/01/2024",
  rent: "320000",
  deposit: "640000",
};
export const auditItems = [
  "Contrat de bail",
  "Historique des paiements",
  "Relances envoyées",
  "Documents locatifs",
  "Chronologie complète",
];
export const analysisSteps = [
  "Document reçu",
  "OCR",
  "Analyse IA",
  "Extraction",
  "Vérification",
];
